# Generated by Django 2.0.4 on 2018-05-19 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ygxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bh', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=11)),
                ('bum', models.IntegerField(choices=[(0, '销售部'), (1, '财务部'), (2, '人事部'), (3, '仓管部')], default=0)),
                ('sfzh', models.CharField(max_length=100)),
                ('gzkh', models.CharField(max_length=100)),
                ('rzsj', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
