# Generated by Django 2.0.4 on 2018-05-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='khxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khbh', models.IntegerField()),
                ('khmc', models.CharField(max_length=20)),
                ('khlx', models.CharField(max_length=10)),
                ('khdj', models.IntegerField()),
                ('khyh', models.CharField(max_length=20)),
                ('yhzh', models.IntegerField()),
                ('xsry', models.CharField(max_length=20)),
                ('lxr', models.CharField(max_length=10)),
                ('tel', models.IntegerField()),
                ('tel2', models.IntegerField()),
                ('dz', models.CharField(max_length=200)),
                ('sfzh', models.CharField(max_length=50)),
            ],
        ),
    ]
